{"name": "Попытка авторизация курьера с неверным логином", "status": "passed", "start": 1748556411743, "stop": 1748556411953, "uuid": "6dd640de-f076-48bd-947f-a73767970e2f", "historyId": "08453b5a03534caba2d9864013784c8e", "testCaseId": "08453b5a03534caba2d9864013784c8e", "fullName": "tests.couriers.test_courier_login.TestCourierLogin#test_authorization_with_invalid_login", "labels": [{"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "EgorLaptop"}, {"name": "thread", "value": "29732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_courier_login"}]}